name: flutter_demo_firebase
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.6.1
  cloud_firestore: ^4.4.2
  firebase_auth: ^4.2.8
  hooks_riverpod: ^2.2.0
  flutter_chat_ui: ^1.6.6
  uuid: ^3.0.4
  flutter_typeahead: ^4.0.0
  flutterfire_ui: ^0.4.1+2
  flutter_facebook_auth: ^4.3.0
  flutter_hooks: ^0.18.4
  google_sign_in: ^5.3.1
  bottom_navy_bar: ^6.0.0
  lottie: ^2.2.0
  riverpod: ^2.2.0
  state_notifier: ^0.7.2+1
  json_serializable: ^6.6.1
  analyzer: ^5.6.0
  expandable: ^5.0.1
  intro_slider: ^4.2.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.3.2
  flutter_native_splash: ^2.2.18
  
flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/chat_hub_logo.png'
  color_dark: '#262626'
  image_dark: 'assets/chat_hub_logo.png'
  fullscreen: true
  android_12:
    icon_background_color: '#FFFFFF'
    image: 'assets/chat_hub_logo.png'
    icon_background_color_dark: '#262626'
    image_dark: 'assets/chat_hub_logo.png'


flutter:
  uses-material-design: true

  assets:
    - assets/